Repository dewi-alliance/hotspot-manufacturers, pull requests merged in 2021-08, with the labels that each got.

#51 Add applications that were missed during import
  applications/bobcat.md
  applications/bobcat/DX83E08.pdf
  applications/clodpi.md
  applications/clodpi/indoor-hotspot-1.png
  applications/pisces-miner.md
Labels: bug, meta

#58 Chipmatrix
  TEMPLATE.md
  chipmatrix.md
Labels: application

#64 Na2He – HIP19 3rd Party Distributor Application
  applications/Na2He
Labels: changes requested, Distributor
